#!/usr/bin/env bash
# Script that configure HAproxy on lb-01 server.

sudo apt-get update
sudo apt-get install -y haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "
listen load-balance
        bind :80
        bind :8080
        mode http
        balance roundrobin
        option httpchk HEAD / HTTP/1.1\r\nHost:\ localhost
        option forwardfor
        server 84504-web-01 18.233.66.188 check port 80
        server 84504-web-02 35.175.134.84 check port 80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
